# Основные настройки
title: "THE B.O.R.S.H"
description: "Bali Open Re-Sources Hub"
author: 
  name: "halosaur"
  email: "sergey.an.mironov@gmail.com"
  
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: dark

  nav_pages:
    - about.md    
    - notes.md

  show_excerpts: false    
    
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/jekyll/minima"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"     



