# Основные настройки
title: "THE B.O.R.S.H"
description: "Bali Open Re-Sources Hub"
url: "https://mas-hakim.github.io"
author: 
  name: Mas Hakim
  email: sergey.an.mironov@gmail.com
lang: "ru"

# ТЕМА 
theme: minima

minima:
  skin: 
    - dark
# Навигация 
  nav_pages:
    - index.md
    - about.md
    - notes.md
    - contacts.md
    
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/jekyll/minima"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"    

# Плагины
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - pages/
  - blog/

permalink: /blog/:title/
